from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def generate_pdf_report(
    filename,
    job_role,
    resume_score,
    ats_score,
    matched_skills,
    missing_skills,
    suggestions,
    ai_analysis=""
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    # =====================
    # TITLE
    # =====================

    content.append(
        Paragraph(
            "SMART RESUME ANALYZER",
            styles["Title"]
        )
    )

    content.append(
        Paragraph(
            "Candidate Assessment Report",
            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            f"Generated On: {datetime.now().strftime('%d-%m-%Y')}",
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    # =====================
    # SUMMARY
    # =====================

    career_readiness = round(
        (resume_score + ats_score) / 2
    )

    if career_readiness >= 90:
        grade = "A+"
    elif career_readiness >= 80:
        grade = "A"
    elif career_readiness >= 70:
        grade = "B"
    elif career_readiness >= 60:
        grade = "C"
    else:
        grade = "D"

    content.append(
        Paragraph(
            f"<b>Target Role:</b> {job_role}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Resume Score:</b> {resume_score}/100",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"<b>ATS Compatibility:</b> {ats_score}%",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Career Readiness:</b> {career_readiness}%",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Resume Grade:</b> {grade}",
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 15)
    )

    # =====================
    # MATCHED SKILLS
    # =====================

    content.append(
        Paragraph(
            "Matched Skills",
            styles["Heading2"]
        )
    )

    for skill in matched_skills:

        content.append(
            Paragraph(
                f"• {skill}",
                styles["Normal"]
            )
        )

    content.append(
        Spacer(1, 12)
    )

    # =====================
    # MISSING SKILLS
    # =====================

    content.append(
        Paragraph(
            "Missing Skills",
            styles["Heading2"]
        )
    )

    for skill in missing_skills:

        content.append(
            Paragraph(
                f"• {skill}",
                styles["Normal"]
            )
        )

    content.append(
        Spacer(1, 12)
    )

    # =====================
    # RECOMMENDATIONS
    # =====================

    content.append(
        Paragraph(
            "Recommendations",
            styles["Heading2"]
        )
    )

    for suggestion in suggestions:

        content.append(
            Paragraph(
                f"• {suggestion}",
                styles["Normal"]
            )
        )

    content.append(
        Spacer(1, 12)
    )

    # =====================
    # AI ANALYSIS
    # =====================

    if ai_analysis:

        content.append(
            Paragraph(
                "AI Resume Analysis",
                styles["Heading1"]
            )
        )

        content.append(
            Spacer(1, 10)
        )

        paragraphs = ai_analysis.split("\n")

        for para in paragraphs:

            para = para.strip()

            if para:

                content.append(
                    Paragraph(
                        para,
                        styles["Normal"]
                    )
                )

                content.append(
                    Spacer(1, 4)
                )

    # =====================
    # FOOTER
    # =====================

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated by Smart Resume Analyzer",
            styles["Italic"]
        )
    )

    doc.build(content)