from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime

def generate_pdf_report(
    filename,
    job_role,
    resume_score,
    ats_score,
    matched_skills,
    missing_skills,
    suggestions,
    ai_analysis=""
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph(
        "SMART RESUME ANALYZER",
        styles["Title"]
    ))

    content.append(
        Paragraph(
            "Candidate Assessment Report",
            styles["Heading2"]
        )
    )


    content.append(
        Spacer(1, 12)
    )
    content.append(
    Paragraph(
        f"Generated On: {datetime.now().strftime('%d-%m-%Y')}",
        styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Target Role: {job_role}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Resume Score: {resume_score}/100",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"ATS Compatibility: {ats_score}%",
            styles["Normal"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Matched Skills",
            styles["Heading2"]
        )
    )

    for skill in matched_skills:

        content.append(
            Paragraph(
                f"• {skill}",
                styles["Normal"]
            )
        )

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Missing Skills",
            styles["Heading2"]
        )
    )

    for skill in missing_skills:

        content.append(
            Paragraph(
                f"• {skill}",
                styles["Normal"]
            )
        )

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Recommendations",
            styles["Heading2"]
        )
    )

    for suggestion in suggestions:

        content.append(
            Paragraph(
                f"• {suggestion}",
                styles["Normal"]
            )
        )
    if ai_analysis:

        content.append(
            Spacer(1, 12)
        )

        content.append(
            Paragraph(
                "AI Resume Analysis",
                styles["Heading1"]
            )
        )

        content.append(
            Spacer(1, 12)
        )

        sections = ai_analysis.split("\n")

        for section in sections:

            section = section.strip()

            if section:

                content.append(
                    Paragraph(
                        section,
                        styles["Normal"]
                    )
                )

                content.append(
                    Spacer(1, 6)
                )
    content.append(
    Spacer(1, 20)
)

    content.append(
        Paragraph(
            "Generated by Smart Resume Analyzer",
            styles["Italic"]
        )
    )
    doc.build(content)